### ISSUE TITLE
xLoRA complete: Swapped 0 LoRA layers (out of 1897 modules)

### ISSUE THREAD

**Issue by Abdullah-kwl** [EricLBuehler/xlora#22]
i am using three Lora adapters r=4 and alpha=64, on model senseable/WestLake-7B-v2, i performed SFT on three adapter ,
I am using BitsAndBytesConfig to quantize my model into 4bit, then I trained 3 lora adapters using this quantized model. 
Now I want to use/test Xlora on a quantized model and pre-trained adapters.

it shows
![Screenshot 2024-03-20 052216](https://github.com/EricLBuehler/xlora/assets/101694671/ec0412dd-6b28-494d-9425-e48bc642bfe2)
: xLoRA complete: Swapped 0 LoRA layers (out of 1897 modules)
Is this normal or there is some error?
Is there might be a bug or unexpected behavior in the function?
Is it because I used a quantized model?
Is there any issue with xlora_depth value or it is irrelevant to this?
Is my model converted into xlora or not?

after running this line model_created.print_trainable_parameters()
output is:
trainable params: 67,149,830 || all params: 7,319,891,974 || trainable%: 0.9174

**Comment by EricLBuehler** [comment]
Hi @Abdullah-kwl, the lack of swapping for a quantized model can be caused by internal QLora* layers. At the moment, `xlora` only supports non quantized layers. If you could provide a simple minimum reproducible code, that would be very helpful for future implementation of support for quantized layers.
